README.md

Matt is love

---

index.ts

Add more phrases :P

---

README.md

Add some reasons of why we love matt!
Add some reasons to the readme for the issues for more reasons we love Matt.
Closes #XXXXX

Update readme.MD for the reasons I love Matt!

---

index.ts
src/index.ts

Give Matt some space
This will allow following types of messages:
1. 
m a t t
2.
m
a
t
t

remove whitespaces before checking for matt

---

src/index.ts

I've rebased and added emoji support in the conditional statement
Closes #12

Add additional condition for emoji

---

README.md
src/index.ts

Updates the readme with a note, adds the emoji checks (they look like ascii, but they're the escaped unicode versions given by discord)
Closes #XXXXX

Update readme, add emoji check

---

sayings.txt

added acronym M.A.T.T. in sayings.txt

---

src/phrases.ts

This PR migrates the latest addition from the `.txt` file to the code.
Closes #XXXXX

Bring text changes to phrases

---

README.md

Adds headers for Luke and Raven!
Closes #XXXXX

Let's spread some love!

---

README.md

Show luke some love

---

README.md

Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>
Give Raven some love in the readme too! They deserve it!
Closes #3

Add some reasons for Raven~!

---

src/index.ts

This PR lets the bot fire if any of the loved people are mentioned. 
This means, if you mention "@Matt", then the bot would respond, "Matt is Amazing!"

Handle mentions

---

.github/workflows/codeql-analysis.yml
.github/workflows/node-ci.yml

tools: new codeql

---

CONTRIBUTING.md

Instructs the user to help set up their application.
Closes #62

Added setup instructions

---

.github/workflows/codeql-analysis.yml
.github/workflows/node-ci.yml
package-lock.json
package.json

chore: maintenance

---

package-lock.json
package.json
src/index.ts
src/server/startServer.ts

Add https endpoint and update ports for nginx
Closes #XXXXX

feat: update ports

---

package-lock.json
package.json
src/config/IntentOptions.ts
src/index.ts

Migrate Discord.js to v13, update other deps since I'm here.
Closes #XXXXX

feat: migrate discord.js to 13

---

src/data/tags.ts

chore: add disqualified tag

---

src/data/tags.ts

Just updated the aliases for the `disqualified` , so that it can answer more more people for the `banned` people, UwU
Closes: idk 🤷🏻 OwO
Hope you merge it or its a valid pr Nick Senpai :) UwU

Just updates the alisases

---

package-lock.json
package.json
src/data/tags.ts
src/modules/sendLove.ts
src/modules/sendTag.ts

Adds a donation cta to embeds, cleans up the tags a bit.
Closes #XXXXX

feat: donation cta

---

src/modules/sendTag.ts

Cleans up the way the tag list appears, adds donation CTA.
Closes #XXXXX

feat: update tag list format

---

package-lock.json
package.json

release: v3.1.2

---

src/modules/sendLove.ts
src/modules/sendTag.ts

feat: add avatar to embed footers

---

package-lock.json
package.json

release: v3.1.3

---

src/data/tags.ts

Track tag :^)

---

src/data/tags.ts

Added a necessary tag (that's more superior than the track tag in every way. Don't tell Walshy I said that :p)
N/A

feat: add shipfaster tag

---

src/data/tags.ts

At some point I'll look in to why the test for this doesn't fail as expected.
Closes #XXXXX

chore: sort tags

---

package-lock.json
package.json

release: v3.1.4

---

src/data/tags.ts

Since this is a common question...
Closes #XXXXX

chore: add customs tag

---

src/modules/sendLove.ts
src/modules/sendTag.ts

chore: update avatar

---

src/data/tags.ts

chore: update tag data

---

src/data/tags.ts

Adds three new tags; win, contribute, and pr-count, the second of which should see some solid regular use.

feat: add more tags

---

src/data/tags.ts

- Additional tag added to `tags.ts` file for use with the Bot 
- Tag specifically answers multiple repeat questions around how to find particular repos in Github with the `hacktoberfest` topic and specific language type
- add to bottom of file, EOF line retained and closing `,` after object retained too
Closes: N/A

language tag added to tags.ts, with content & title defined, and additional alias

---

src/data/tags.ts

Added three more FAQ entries (maintainer-swag, check-exclusion, own-repo), and cleaned up the grammar in the language entry (as per discord).
Not entirely sure about the wording on own-repo. I feel like it lacks something, but without really seeing what that something is

feat: more FAQ entries

---

src/commands/faq.ts

fix: formatting of user mention

---

src/commands/faq.ts
src/data/tags.ts
src/events/onInteractionCreate.ts
src/interfaces/Tag.ts
test/data.spec.ts

feat: use questions instead of names

---

package-lock.json
package.json
src/commands/report.ts
src/commands/token.ts
src/index.ts
src/interfaces/Bot.ts

feat: report commands

---

src/commands/token.ts

fix: prevent porg from being stinky

---

src/data/tags.ts

Adds a small message for queries regarding Holopin. I see a ton of questions on the HF server that are one of the following:
- Where are my Holopins?
- Why are my Holopins not showing up?
and quite often, they have either not opted-in to it, or it's in their spam :/

feat: Added message for Holopin related questions

---

src/events/onMessageEdit.ts
src/index.ts

feat: handle message edits as well

---

src/modules/checkProject.ts

Tweaks the copy to make it clearer why a user's message has been removed by the logic.
N/A

Tweak message copy for project-sharing logic

---

.github/workflows/codeql-analysis.yml
.github/workflows/node-ci.yml
package.json

chore: node 18

---

src/commands/faq.ts
src/modules/sendLove.ts

chore: update footer

---

src/commands/faq.ts
src/modules/sendLove.ts

chore: use domain redirect

---

package-lock.json
package.json
src/commands/report.ts
src/commands/token.ts
src/utils/registerCommands.ts

chore: update dependencies

---

.github/workflows/node-ci.yml
src/utils/errorHandler.ts

chore: add eslint-disable action

---

src/commands/faq.ts
src/modules/sendLove.ts

chore: update chat link

---

src/config/ProjectRegex.ts
test/config/ProjectRegex.spec.ts

chore: replace boundary with custom pattern

---

.github/workflows/codeql-analysis.yml
.github/workflows/node-ci.yml
package.json

chore: move to node 20

---

src/modules/isInDatabase.ts

fix: inverted timestamp condition

---

src/config/ProjectRegex.ts
test/config/ProjectRegex.spec.ts
test/modules/parseProjectLink.spec.ts

feat: handle trailing slash properly

---

src/commands/report.ts

Updated the event ID in the reporting URL from 4 to 5
Closes #741

Update the event ID from 4 to 5 in report.ts

---

src/events/onMessage.ts
src/events/onMessageEdit.ts
src/modules/checkProject.ts

fix: use a flag to ignore edited messages for repeat posting

---

CONTRIBUTING.md

Changed non working link to -> https://docs.nhcarrigan.com/#/projects/we-love-hacktoberfest/contributing
Closes #749

docs: update contributing link

---

src/commands/holopin.ts

feat: display holopins

---

src/commands/holopin.ts

feat: upload image directly

---

package.json
pnpm-lock.yaml
src/commands/faq.ts
src/commands/holopin.ts
src/commands/search.ts
src/config/ProjectRegex.ts
src/helpers/getRandom.ts
src/index.ts
src/modules/checkProject.ts
src/utils/loadCommands.ts
test/config/ProjectRegex.spec.ts
tsconfig.json

feat: handle repeated repository links

---

src/data/loveData.ts

I have added new entries to the loveData array in this pull request. These entries include information about the following projects and organizations:
IllaCloud: A project represented by the emoji "I L L A C L O U D."
Amplication: A project represented by the emoji "A M P L I C A T I O N."
Runme: A project represented by the emoji "R U N M E."
OpenSauced: A project represented by the emoji "O P E N S A U C E D."
MLH: A project represented by the emoji "M L H."
HuggingFace: A project represented by the emoji "H U G G I N G F A C E."
Closes #723

docs: Added new sponsors to loveData.ts #723

---

src/modules/checkProject.ts

This gives us the ability to reply to messages in the channel. For example, letting a member know that their project was removed for not being in line with the hacktoberfest values.
Closes #XXXXX

feat: ignore helpers in project validation

---

src/data/tags.ts

chore: add some new faq

---

src/config/ProjectRegex.ts
src/modules/parseProjectLink.ts
test/config/ProjectRegex.spec.ts
test/modules/parseProjectLink.spec.ts

fix(regex): allow markdown and links to full issue page

---

test/__statics__/RegexRegressions.ts
test/config/ProjectRegex.spec.ts

This'll make it easier to dump false positives from the logs directly into the test suite.
Closes #XXXXX

feat(tools): infrastructure for full regression testing

---

src/data/tags.ts

Signed-off-by: Ilenia M <nethleen@gmail.com>
I have added the tag about GitHub caching holopin boards.
Closes #782

feat: add tag about github caching holopin boards

---

src/utils/errorHandler.ts
test/utils/errorHandler.spec.ts

feat: include username and avatar in webhook
